"""initial schema

Revision ID: 98012760f449
Revises: 
Create Date: 2026-03-18 19:21:33.172136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98012760f449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuer',
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_incorporation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domicile_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lei', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_shell_flag', sa.Boolean(), nullable=False),
    sa.Column('is_bankrupt_flag', sa.Boolean(), nullable=False),
    sa.Column('is_liquidating_flag', sa.Boolean(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('issuer_id')
    )
    op.create_table('user',
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_clerk_user_id'), 'user', ['clerk_user_id'], unique=True)
    op.create_table('api_key',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuer_classification_history',
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('classification_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuer_name_history',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security',
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('security_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('security_subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('share_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('par_value', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary_equity_flag', sa.Boolean(), nullable=False),
    sa.Column('underlying_security_id', sa.Uuid(), nullable=True),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.ForeignKeyConstraint(['underlying_security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('security_id')
    )
    op.create_table('corporate_action',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('ratio_from', sa.Float(), nullable=True),
    sa.Column('ratio_to', sa.Float(), nullable=True),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('corporate_action_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('corporate_action_id')
    )
    op.create_table('listing',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('venue_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mic_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('is_primary_listing_flag', sa.Boolean(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('security_identifier_history',
    sa.Column('id_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venue_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('is_primary_flag', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shares_outstanding_history',
    sa.Column('security_id', sa.Uuid(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('public_float', sa.Integer(), nullable=True),
    sa.Column('authorized_shares', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('value_source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_status_history',
    sa.Column('effective_start_date', sa.Date(), nullable=False),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('listing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caveat_emptor_flag', sa.Boolean(), nullable=False),
    sa.Column('unsolicited_quotes_only_flag', sa.Boolean(), nullable=False),
    sa.Column('shell_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('sec_suspension_flag', sa.Boolean(), nullable=False),
    sa.Column('bankruptcy_flag', sa.Boolean(), nullable=False),
    sa.Column('current_information_flag', sa.Boolean(), nullable=False),
    sa.Column('transfer_agent_verified_flag', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.listing_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_security_map',
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=True),
    sa.Column('security_id', sa.Uuid(), nullable=True),
    sa.Column('listing_id', sa.Uuid(), nullable=True),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('mapping_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuer.issuer_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.listing_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_security_map')
    op.drop_table('listing_status_history')
    op.drop_table('shares_outstanding_history')
    op.drop_table('security_identifier_history')
    op.drop_table('listing')
    op.drop_table('corporate_action')
    op.drop_table('security')
    op.drop_table('issuer_name_history')
    op.drop_table('issuer_classification_history')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_user_clerk_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('issuer')
    # ### end Alembic commands ###
